### ISSUE TITLE
GR 1: Remove BreakGlass Account Name from Comments

### ISSUE THREAD

**Issue by MathesonSho** [alalvi00/GuardrailsSolutionAccelerator#5]
**Describe the solution you'd like**

![image](https://github.com/alalvi00/GuardrailsSolutionAccelerator/assets/111992749/7b708326-7692-4779-862f-4bfc49776d59)

Guardrail 1 Control ItemName "Break Glass Account Owners Contact information (R)" returns comments with the variable given by departments. 

i.e., BreakGlass Account: tim@BG.on.microsoft.com would return "BG account tim@BG.on.microsoft.com doesn't have a manager"

**Describe alternatives you've considered**
- First choice would be for us to follow a similar concept to credit cards where it won't ask is this your BG account? tim@BG.on.microsoft.com
Instead it would return t##@##.##.microsoft.com
- Remove the variable reference to be generic ("One BG account doesn't have a manager" or "Both BG Accounts do not have a manager")
- Replace with an indicator such as "BG Account 1 doesn't have a manager" or "Both BG Account 1 and Account 2 do not have a manager"

**Comment by alalvi00** [comment]
https://github.com/Azure/GuardrailsSolutionAccelerator/pull/446
