### ISSUE TITLE
GR 11: Severity Notifications to a Primary Email - Comment Error

### ISSUE THREAD

**Issue by MathesonSho** [alalvi00/GuardrailsSolutionAccelerator#7]
![image](https://github.com/alalvi00/GuardrailsSolutionAccelerator/assets/111992749/29241f26-4912-445d-b042-73d6202770f9)

This control should only be looking for 'SeverityNotificationToEmailConfigured.txt' . Could the details/ comment mentioning MOU is also required be removed? 

Ensure logic matches comments once removed as well

**Comment by alalvi00** [comment]
Fixed
